services:
  - type: web
    name: subtitle-generator
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    region: oregon
    build:
      pythonVersion: 3.10.13
